//
// Created by Administrator on 2017/6/29.
//

#ifndef NDKTEST_COM_BEIING_NDKTEST_NATIVEFUNCTION_H
#define NDKTEST_COM_BEIING_NDKTEST_NATIVEFUNCTION_H

#endif //NDKTEST_COM_BEIING_NDKTEST_NATIVEFUNCTION_H
